{{- if .Values.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pangolin.fullname" . }}-secret
  labels:
    {{- include "pangolin.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  PANGOLIN_JWT_SECRET: {{ .Values.secrets.PANGOLIN_JWT_SECRET | b64enc | quote }}
  PANGOLIN_ROOT_PASSWORD: {{ .Values.secrets.PANGOLIN_ROOT_PASSWORD | b64enc | quote }}
{{- end }}
